MODEL:
  LSTM: True
  MAX_ITER: 100
  TASK: addition
  MAX_ITER: 20
  CONTROLLER:
    HIDDEN_SIZE: 512
ACT:
  PENALTY_COEF: 0.01
SOLVER:
  EPOCHS: 256
  LR: 0.01
INPUT:
  DIM: 50
  SEQ_LEN: 5
OUTPUT:
  DIM: 66
DATALOADER:
  BATCH_SIZE: 32
  TRAIN_SAMPLES: 625000
SAVE: False
