MODEL:
  LSTM: True
  RNN_BASELINE: True
  MAX_ITER: 1
  TASK: addition
  CONTROLLER:
    HIDDEN_SIZE: 512
ACT:
  PENALTY_COEF: 0.0
SOLVER:
  EPOCHS: 256
  LR: 0.001
  GRAD_CLIP: 0.0
INPUT:
  DIM: 50
  SEQ_LEN: 5
OUTPUT:
  DIM: 66
DATALOADER:
  BATCH_SIZE: 32
  TRAIN_SAMPLES: 625000
SAVE: False
